---
abstract: 'Transformation from MARC XML to RDA for NKC demo project.'
author:
  - 'Michal Josef Spacek <skim@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.36
  Test::More: 0
  Test::NoWarnings: 0
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.21'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: NKC-Transform-MARC2RDA
no_index:
  directory:
    - inc
    - share
    - t
    - xt
requires:
  Class::Utils: 0
  File::Share: 0
  Perl6::Slurp: 0
  XML::Saxon::XSLT3: 0
  perl: 5.8.0
resources:
  bugtracker: https://github.com/michal-josef-spacek/NKC-Transform-MARC2RDA/issues
  homepage: https://github.com/michal-josef-spacek/NKC-Transform-MARC2RDA
  license: http://opensource.org/licenses/bsd-license.php
  repository: git://github.com/michal-josef-spacek/NKC-Transform-MARC2RDA
version: '0.02'
